### ISSUE TITLE
[Bug] Impossible to run storybook with latest update

### ISSUE THREAD

**Issue by qlaffont** [storybookjs/solidjs#18]
### Describe the bug

I have try to upgrade to latest version of solidjs but it doesn't work

```
=> Failed to build the preview
Error: Missing "./internal/preview/runtime" specifier in "storybook" package
    at e (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:25)
    at n (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:631)
    at o (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:1301)
    at resolveExportsOrImports (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16481:18)
    at resolveDeepImport (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16494:25)
    at tryNodeResolve (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16324:18)
    at ResolveIdContext.resolveId (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16109:19)
    at EnvironmentPluginContainer.resolveId (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47137:17)
    at async resolve (file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47678:12)
    at async file://./node_modules/.pnpm/vite@6.0.5_@types+node@20.8.5_jiti@2.4.2_sass@1.83.0_terser@5.21.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47694:22
```

### Environment

![Image](https://github.com/user-attachments/assets/6fda16f4-135d-4cb3-9f9f-d3552ae468a2)

**Comment by SinnerAir** [comment]
I have the same problem (pnpm 9.15.1, vite 6.0.5)
```
> storybook dev -p 6006

@storybook/core v8.4.7

info => Starting manager..
info => Starting preview..
=> Failed to build the preview
Error: Missing "./internal/preview/runtime" specifier in "storybook" package
    at e (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:25)
    at n (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:631)
    at o (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:1301)
    at resolveExportsOrImports (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16481:18)
    at resolveDeepImport (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16494:25)
    at tryNodeResolve (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16324:18)
    at ResolveIdContext.resolveId (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16109:19)
    at EnvironmentPluginContainer.resolveId (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47137:17)
    at async resolve (file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47678:12)
    at async file:///D:/projects/apps/node_modules/.pnpm/vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_lightningcss@1.28.2_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47694:22

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by SinnerAir** [comment]
I want to share a temporary solution. I visited the site [https://new-storybook.netlify.app/](https://new-storybook.netlify.app/), where I followed the link to the demo version for SolidJS. I updated the package.json
```
    "@storybook/addon-essentials": "^8.5.0-beta.5",
    "@storybook/addon-interactions": "^8.5.0-beta.5",
    "@storybook/blocks": "^8.5.0-beta.5",
    "@storybook/test": "^8.5.0-beta.5",
    "storybook": "^8.5.0-beta.5",
```
and the error was corrected

**Comment by yefu24324** [comment]
package.json add
```
  "pnpm": {
    "overrides": {
      "@storybook/builder-vite": "~8.4.6"
    }
  }
```

**Comment by yefu24324** [comment]
The error occurs because the dependency @storybook/builder-vite@next was installed, resulting in the non-stable version 5.0.0-beta. This library is not yet compatible.

https://github.com/storybookjs/solidjs/blob/12e463340765704d87170a85afaf03a8af1ce71a/packages/frameworks/solid-vite/package.json#L53 

If you are using pnpm, you can try
```
  "pnpm": {
    "overrides": {
      "@storybook/builder-vite": "~8.4.6"
    }
  }
```

**Comment by DHFW** [comment]
I had installed storybook where every dependency had a version with the `^` sign.
```json
"@storybook/addon-essentials": "8.4.7",
    "@storybook/addon-interactions": "^8.4.7",
    "@storybook/builder-vite": "^8.4.7",
    "@storybook/core-server": "8.4.7",
    "@storybook/experimental-nextjs-vite": "^8.4.7",
    "@storybook/jest": "^0.2.3",
    "@storybook/nextjs": "8.4.7",
    "@storybook/react": "^8.4.7",
    "@storybook/react-vite": "^8.4.7",
    "@storybook/test": "^8.4.7",
```

When running `npm install`, some of these deps stayed on "8.4.7", while other were updated to the latest patch version. This caused issues where the error message was `Error: Missing "./internal/preview/runtime" specifier in "storybook" package`.

I fixed it with help of this issue and deleted node_modules, package-lock.json and setting all the packages in the package.json file to the same and fixed version: 

```json
"@storybook/addon-essentials": "8.4.7",
    "@storybook/addon-interactions": "8.4.7",
    "@storybook/builder-vite": "8.4.7",
    "@storybook/core-server": "8.4.7",
    "@storybook/experimental-nextjs-vite": "8.4.7",
    "@storybook/jest": "0.2.3",
    "@storybook/nextjs": "8.4.7",
    "@storybook/react": "8.4.7",
    "@storybook/react-vite": "8.4.7",
    "@storybook/test": "8.4.7",
```

**Comment by kachurun** [comment]
You can try using [create-solid-storybook](https://www.npmjs.com/package/create-solid-storybook). I hope it may help.

**Comment by alemesa** [comment]
> You can try using [create-solid-storybook](https://www.npmjs.com/package/create-solid-storybook). I hope it may help.

This fixed all my issues, thx you ❤
